.TH SECRET 1
.SH NAME
secret \- Tool for encrypted communication via ICMP protocol 
.SH SYNOPSIS
.B secret
[\fB\-r\fR \fIFILE\fR]
[\fB\-s\fR \fIHOSTNAME\fR]
[\fB\-l\fR \fIlistener\fR]
.SH DESCRIPTION
.B secret
either encrypts file and sends it to specified hostname via ICMP echo requests packets or listens to such packets in listener mode that decrypts those packets and saves them to the respective file.
.SH OPTIONS
.TP
.BR \-r =\fIFILE\fR
File to transfer
.TP
.BR \-s =\fIHOSTNAME\fR
Server hostname
.TP
.BR \-l =\fIlistener\fR
Listener mode
.SH Build
\f[CR]make clean\fP - Clean files generated during build process.
.br
\f[CR]make secret\fP - Build project.
.br
\f[CR]make\fP - Run secret target.
.SH Run
.EX
make
sudo ./secret -l
sudo ./secret -r some.file -s localhost
sudo ./secret -r some.file -s ::1
.SH Files
.EX
Makefile
secret.1
manual.pdf
main.cpp
.SH Improvements
.IP \[bu] 2
Transfer status in output
.IP \[bu]
Simultaneous active transfers on server
